/**
 * Seed Cloudflare D1 (remote). Preserves system_backups.
 *
 *   node src/db/seed-remote.mjs
 *   pnpm db:seed:remote
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { scryptAsync } from "@noble/hashes/scrypt";

const __dirname = dirname(fileURLToPath(import.meta.url));
const N = 2048, r = 8, p = 1, DK_LEN = 32;

function b64(bytes) {
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return Buffer.from(s, "binary").toString("base64url");
}

async function hash(password) {
  const salt = new Uint8Array(16);
  crypto.getRandomValues(salt);
  const dk = await scryptAsync(password, salt, { N, r, p, dkLen: DK_LEN });
  return `scrypt$${N}$${r}$${p}$${b64(salt)}$${b64(dk)}`;
}

function esc(s) {
  return String(s).replace(/'/g, "''");
}

async function main() {
  console.log("[seed-remote] hashing passwords…");
  const adminHash = await hash("Admin1234!");
  const patrolHash = await hash("Patrol123!");

  const cpfId = "cpf000000000001";
  const wbs1 = "sec000000000001";
  const wbs2 = "sec000000000002";
  const wbs3 = "sec000000000003";

  let sql = `-- Generated by seed-remote.mjs — DO NOT hand-edit
-- NEVER deletes system_backups

CREATE TABLE IF NOT EXISTS system_backups (
  id text PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  created_at text NOT NULL DEFAULT (datetime('now')),
  created_by_call_sign text NOT NULL,
  created_by_patroller_id text,
  label text,
  byte_size integer NOT NULL DEFAULT 0,
  table_counts text,
  payload text NOT NULL
);

DELETE FROM message_channel_members;
DELETE FROM message_reads;
DELETE FROM messages;
DELETE FROM message_channels;
DELETE FROM push_tokens;
DELETE FROM audit_log;
DELETE FROM patrol_escalation_events;
DELETE FROM patrol_breadcrumbs;
DELETE FROM patrol_members;
DELETE FROM patrols;
DELETE FROM devices;
DELETE FROM login_attempts;
DELETE FROM next_of_kin;
DELETE FROM incidents;
DELETE FROM emergency_services;
DELETE FROM residents;
DELETE FROM vehicles;
DELETE FROM live_pins;
DELETE FROM patrollers;
DELETE FROM sectors;
DELETE FROM cpfs;

INSERT INTO cpfs (id, name, province) VALUES ('${cpfId}', 'Wierdabrug CPF', 'Gauteng');

INSERT INTO sectors (id, cpf_id, name, code) VALUES
  ('${wbs1}', '${cpfId}', 'WBS1', 'WBS1'),
  ('${wbs2}', '${cpfId}', 'WBS2', 'WBS2'),
  ('${wbs3}', '${cpfId}', 'WBS3', 'WBS3');

INSERT INTO patrollers (id, cpf_id, sector_id, call_sign, name, phone, address, password_hash, access_level, status) VALUES
  ('pat000000000000', '${cpfId}', '${wbs1}', 'SYS01', 'System Admin', '+27 72 000 0000', '1 CPF Street, Valhalla', '${esc(adminHash)}', 'system_admin', 'active'),
  ('pat000000000001', '${cpfId}', '${wbs1}', 'WV01', 'WBS1 Admin', '+27 72 000 0001', '1 CPF Street, Valhalla', '${esc(adminHash)}', 'admin', 'active'),
  ('pat000000000002', '${cpfId}', '${wbs1}', 'WV46', 'Adele Jansen van Vuuren', '+27 72 111 1111', '46 Sector 1 Road, Valhalla', '${esc(patrolHash)}', 'call_centre_agent', 'active'),
  ('pat000000000003', '${cpfId}', '${wbs1}', 'WC29', 'Theuns Barnardt', '+27 72 235 2283', '53a Meteor Rd Valhalla', '${esc(patrolHash)}', 'patroller', 'active'),
  ('pat000000000004', '${cpfId}', '${wbs1}', 'WC46', 'Adele Barnardt', '+27 72 222 2222', '53a Meteor Rd Valhalla', '${esc(patrolHash)}', 'patroller', 'active'),
  ('pat000000000005', '${cpfId}', '${wbs2}', 'WV02', 'WBS2 Admin', '+27 72 000 0002', '2 Sector Road', '${esc(adminHash)}', 'admin', 'active'),
  ('pat000000000006', '${cpfId}', '${wbs3}', 'WV03', 'WBS3 Admin', '+27 72 000 0003', '3 Sector Road', '${esc(adminHash)}', 'admin', 'active');

INSERT INTO next_of_kin (patroller_id, name, relationship, phone) VALUES
  ('pat000000000003', 'Adele Barnardt', 'Spouse', '+27 72 222 2222'),
  ('pat000000000004', 'Theuns Barnardt', 'Spouse', '+27 72 235 2283');

INSERT INTO vehicles (id, cpf_id, sector_id, registration, description, last_odometer, status) VALUES
  ('veh000000000001', '${cpfId}', '${wbs1}', 'CPF 001 GP', 'Primary patrol bakkie', 123456, 'available'),
  ('veh000000000002', '${cpfId}', '${wbs1}', 'CPF 002 GP', 'Backup vehicle', 54321, 'available'),
  ('veh000000000003', '${cpfId}', '${wbs2}', 'CPF 201 GP', 'WBS2 patrol', 10000, 'available'),
  ('veh000000000004', '${cpfId}', '${wbs3}', 'CPF 301 GP', 'WBS3 patrol', 20000, 'available');
`;

  for (let i = 0; i < 12; i++) {
    const sector = i < 8 ? wbs1 : i < 10 ? wbs2 : wbs3;
    sql += `INSERT INTO residents (cpf_id, sector_id, name, phone, address) VALUES ('${cpfId}', '${sector}', 'Resident ${i + 1}', '+27 72 500 ${(1000 + i).toString().padStart(4, "0")}', '${i + 1} Meteor Rd Valhalla');\n`;
  }

  sql += `
INSERT INTO emergency_services (cpf_id, name, service_type, primary_number, address, priority, sensitive, verified_at) VALUES
  ('${cpfId}', 'Valhalla SAPS', 'police', '012 654 0100', 'Valhalla, Centurion', 10, 0, datetime('now')),
  ('${cpfId}', 'Netcare 911', 'ambulance', '082 911', NULL, 20, 0, datetime('now')),
  ('${cpfId}', 'Centurion Fire Brigade', 'fire', '012 358 6666', NULL, 30, 0, datetime('now')),
  ('${cpfId}', 'ADT Armed Response', 'armed_response', '086 1 12 12 12', NULL, 40, 0, datetime('now')),
  ('${cpfId}', 'Unitas Hospital', 'hospital', '012 677 8000', 'Lyttelton Manor', 50, 0, datetime('now')),
  ('${cpfId}', 'Wierdabrug Ops Room', 'ops_room', '072 999 8888', NULL, 5, 0, datetime('now'));

INSERT INTO incidents (cpf_id, sector_id, type, severity, lat, lng, occurred_at) VALUES
  ('${cpfId}', '${wbs1}', 'theft', 'medium', -25.840, 28.180, datetime('now', '-1 day')),
  ('${cpfId}', '${wbs1}', 'burglary', 'high', -25.843, 28.176, datetime('now', '-3 days')),
  ('${cpfId}', '${wbs1}', 'suspicious_person', 'low', -25.841, 28.179, datetime('now', '-5 days')),
  ('${cpfId}', '${wbs2}', 'alarm', 'medium', -25.844, 28.177, datetime('now', '-10 days')),
  ('${cpfId}', '${wbs2}', 'traffic_incident', 'low', -25.839, 28.181, datetime('now', '-15 days')),
  ('${cpfId}', '${wbs3}', 'theft', 'high', -25.845, 28.175, datetime('now', '-30 days')),
  ('${cpfId}', '${wbs3}', 'burglary', 'medium', -25.838, 28.182, datetime('now', '-60 days'));
`;

  const out = join(__dirname, "_remote-seed.sql");
  writeFileSync(out, sql, "utf8");
  console.log(`[seed-remote] wrote ${out}`);

  console.log("[seed-remote] executing on Cloudflare D1 (remote)…");
  const result = spawnSync(
    "npx",
    ["wrangler", "d1", "execute", "patrol-log-db", "--remote", `--file=${out}`],
    { cwd: join(__dirname, "../.."), stdio: "inherit", shell: true },
  );
  if (result.status !== 0) {
    throw new Error(`wrangler d1 execute failed with code ${result.status}`);
  }

  console.log(`
[seed-remote] done! Accounts (password Admin1234! for admins, Patrol123! for others):
  SYS01 / Admin1234!   → system_admin (all sectors)
  WV01  / Admin1234!   → WBS1 sector admin
  WV02  / Admin1234!   → WBS2 sector admin
  WV03  / Admin1234!   → WBS3 sector admin
  WV46  / Patrol123!   → call centre (WBS1)
  WC29  / Patrol123!   → patroller (WBS1)
  WC46  / Patrol123!   → patroller (WBS1)
  system_backups table was NOT wiped.
`);
}

main().catch((err) => {
  console.error("[seed-remote] failed:", err);
  process.exit(1);
});
