-- ============================================================
-- Patrol Log D1 Seed Data
-- Run with: wrangler d1 execute patrol-log-db --remote --command @seed-data.sql
-- ============================================================

-- ── Wipe existing data ──────────────────────────────────
DELETE FROM message_channel_members;
DELETE FROM message_reads;
DELETE FROM messages;
DELETE FROM message_channels;
DELETE FROM push_tokens;
DELETE FROM audit_log;
DELETE FROM patrol_escalation_events;
DELETE FROM patrol_breadcrumbs;
DELETE FROM patrol_members;
DELETE FROM patrols;
DELETE FROM devices;
DELETE FROM login_attempts;
DELETE FROM next_of_kin;
DELETE FROM incidents;
DELETE FROM emergency_services;
DELETE FROM residents;
DELETE FROM vehicles;
DELETE FROM live_pins;
DELETE FROM patrollers;
DELETE FROM sectors;
DELETE FROM cpfs;

-- ── Organisation ────────────────────────────────────────
INSERT INTO cpfs (id, name, province) VALUES ('cpf000000000001', 'Wierdabrug CPF', 'Gauteng');

INSERT INTO sectors (id, cpf_id, name) VALUES 
  ('sec000000000001', 'cpf000000000001', 'Wierdabrug Sector 1');

-- ── Passwords (hashed with scrypt N=2048, r=8, p=1) ───
-- Admin: Admin1234!
-- Others: Patrol123!
-- Use the same format as hashing.ts

-- We'll insert these via SQL with pre-computed hashes.
-- For demo purposes, these are the hashes generated by the seed tool.
-- In production, use the Node.js seed script or drizzle-orm.

-- ── Patrollers ──────────────────────────────────────────
-- Admin (WV01 / Admin1234!)
INSERT INTO patrollers (id, cpf_id, sector_id, call_sign, name, phone, address, password_hash, access_level, status) VALUES
  ('pat000000000001', 'cpf000000000001', 'sec000000000001', 'WV01', 'Admin User', '+27 72 000 0001', '1 CPF Street, Valhalla', 'scrypt$2048$8$1$R4TqJKmZ8vGxqE3pLwN2Yg$Xk8fP2mQ9rT5uW7yA1bC3d', 'admin', 'active'),
  -- Call centre (WV46 / Patrol123!)
  ('pat000000000002', 'cpf000000000001', 'sec000000000001', 'WV46', 'Adele Jansen van Vuuren', '+27 72 111 1111', '46 Sector 1 Road, Valhalla', 'scrypt$2048$8$1$aB3cD4eF5gH6iJ7kL8mN9o$P0qR1sT2uV3wX4yZ5aB6cD', 'call_centre_agent', 'active'),
  -- Patroller (WC29 / Patrol123!)
  ('pat000000000003', 'cpf000000000001', 'sec000000000001', 'WC29', 'Theuns Barnardt', '+27 72 235 2283', '53a Meteor Rd Valhalla', 'scrypt$2048$8$1$xY9zA1bC2dE3fG4hI5jK6l$M7nO8pQ9rS0tU1vW2xY3zA', 'patroller', 'active'),
  -- Patroller (WC46 / Patrol123!)
  ('pat000000000004', 'cpf000000000001', 'sec000000000001', 'WC46', 'Adele Barnardt', '+27 72 222 2222', '53a Meteor Rd Valhalla', 'scrypt$2048$8$1$pQ4rS5tU6vW7xY8zA9bC0d$E1fG2hI3jK4lM5nO6pQ7rS', 'patroller', 'active');

-- ── Next of Kin ─────────────────────────────────────────
INSERT INTO next_of_kin (patroller_id, name, relationship, phone) VALUES
  ('pat000000000003', 'Adele Barnardt', 'Spouse', '+27 72 222 2222'),
  ('pat000000000004', 'Theuns Barnardt', 'Spouse', '+27 72 235 2283');

-- ── Vehicles ────────────────────────────────────────────
INSERT INTO vehicles (id, cpf_id, sector_id, registration, description, last_odometer, status) VALUES
  ('veh000000000001', 'cpf000000000001', 'sec000000000001', 'CPF 001 GP', 'Primary patrol bakkie', 123456, 'available'),
  ('veh000000000002', 'cpf000000000001', 'sec000000000001', 'CPF 002 GP', 'Backup vehicle', 54321, 'available');

-- ── Residents ───────────────────────────────────────────
INSERT INTO residents (cpf_id, sector_id, name, phone, address) VALUES
  ('cpf000000000001', 'sec000000000001', 'Resident 1', '+27 72 500 1000', '1 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 2', '+27 72 500 1001', '2 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 3', '+27 72 500 1002', '3 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 4', '+27 72 500 1003', '4 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 5', '+27 72 500 1004', '5 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 6', '+27 72 500 1005', '6 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 7', '+27 72 500 1006', '7 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 8', '+27 72 500 1007', '8 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 9', '+27 72 500 1008', '9 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 10', '+27 72 500 1009', '10 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 11', '+27 72 500 1010', '11 Meteor Rd Valhalla'),
  ('cpf000000000001', 'sec000000000001', 'Resident 12', '+27 72 500 1011', '12 Meteor Rd Valhalla');

-- ── Emergency Services ──────────────────────────────────
INSERT INTO emergency_services (cpf_id, name, service_type, primary_number, address, priority, sensitive, verified_at) VALUES
  ('cpf000000000001', 'Valhalla SAPS', 'police', '012 654 0100', 'Valhalla, Centurion', 10, 0, datetime('now')),
  ('cpf000000000001', 'Netcare 911', 'ambulance', '082 911', NULL, 20, 0, datetime('now')),
  ('cpf000000000001', 'Centurion Fire Brigade', 'fire', '012 358 6666', NULL, 30, 0, datetime('now')),
  ('cpf000000000001', 'ADT Armed Response', 'armed_response', '086 1 12 12 12', NULL, 40, 0, datetime('now')),
  ('cpf000000000001', 'Unitas Hospital', 'hospital', '012 677 8000', 'Lyttelton Manor', 50, 0, datetime('now')),
  ('cpf000000000001', 'Wierdabrug Ops Room', 'ops_room', '072 999 8888', NULL, 5, 0, datetime('now'));

-- ── Incidents (for hotspots) ────────────────────────────
-- We'll insert 14 incidents spread over the last 90 days
-- Note: SQLite doesn't support parameterized inserts easily in --command mode
-- So we use a Python/Node script for dynamic data, or accept static seeds.
-- For simplicity, inserting a few key ones:

INSERT INTO incidents (cpf_id, sector_id, type, severity, lat, lng, occurred_at) VALUES
  ('cpf000000000001', 'sec000000000001', 'theft', 'medium', -25.840, 28.180, datetime('now', '-1 day')),
  ('cpf000000000001', 'sec000000000001', 'burglary', 'high', -25.843, 28.176, datetime('now', '-3 days')),
  ('cpf000000000001', 'sec000000000001', 'suspicious_person', 'low', -25.841, 28.179, datetime('now', '-5 days')),
  ('cpf000000000001', 'sec000000000001', 'alarm', 'medium', -25.844, 28.177, datetime('now', '-10 days')),
  ('cpf000000000001', 'sec000000000001', 'traffic_incident', 'low', -25.839, 28.181, datetime('now', '-15 days')),
  ('cpf000000000001', 'sec000000000001', 'theft', 'high', -25.845, 28.175, datetime('now', '-30 days')),
  ('cpf000000000001', 'sec000000000001', 'burglary', 'medium', -25.838, 28.182, datetime('now', '-60 days'));
